### ISSUE TITLE
Error Importing Solution

### ISSUE THREAD

**Issue by dim895** [jeromebq/PCF_AddressAPI#10]
Hello,

Thanks for your quick reply; following your resolution yesterday  #9  I tried to import the solution again but have this error. 

I tried on a new trial environment as well as an existing one. I have the same  #problem.
I am unable to import the solution and have this error.

Solution "AddressAPI_Solution" failed to import: Import Solution Failed: CustomControl with name failed to import with error: The import manifest file is invalid. XSD validation failed with the following error: 'The import manifest file is invalid. XSD validation failed with the following error: 'The 'version' attribute is invalid - The value '2.0.0.0' is invalid according to its datatype 'versionType' - The Pattern constraint failed.'."'."

I have added the xml in case you need it.

Thanks in advance
[importlog_AddressAPI_Solution_1_0.xlsx](https://github.com/jeromebq/PCF_AddressAPI/files/5579207/importlog_AddressAPI_Solution_1_0.xlsx)

**Comment by jeromebq** [comment]
Hello, 

Sorry for errors, I tried to solved it tomorrow

**Comment by jeromebq** [comment]
Hello,

the issue is solved. Please confirm me that is ok for you.

Thanks

**Comment by dim895** [comment]
It's perfect Thank you!!
