### ISSUE TITLE
Erreur à l'import de la solution

### ISSUE THREAD

**Issue by jeandubreuil1984** [jeromebq/PCF_AddressAPI#11]
J'ai bien récupéré la solution managée mais j'ai une erreur à l'import.
Je suis sur la version online (9.1.0.25245).

Est-ce que cela fonctionne pour vous?

**Comment by jeromebq** [comment]
Bonjour,
Je n'ai pas eu de message de mon côté ! J'essaie de reproduire demain. Avez vous un screen du message d'erreur, ou le fichier de log ? 
Merci

**Comment by jeromebq** [comment]
Bonjour,

Le bug a été corrigé.
Merci pour votre retour.

Jérôme
