### ISSUE TITLE
Adding The control twice

### ISSUE THREAD

**Issue by dim895** [jeromebq/PCF_AddressAPI#9]
Hello,

First of all, thanks for the PCF!

I need to add the control twice on a form, because customer needs to fill two addresses instead of one.

When adding the control twice, when you do your search on one field the result is copied everywhere, so I cannot have two separate searches.

Is there a way to fix this? I have added a short video in zip file so that it is more clear

[Account_ Account_ Alpine Ski House (sample) - Power Apps - Google Chrome 2020-11-17 09-13-41.zip](https://github.com/jeromebq/PCF_AddressAPI/files/5552112/Account_.Account_.Alpine.Ski.House.sample.-.Power.Apps.-.Google.Chrome.2020-11-17.09-13-41.zip)

**Comment by jeromebq** [comment]
Hello,

Thanks for your message.
I will check this next week.

Jerome

**Comment by jeromebq** [comment]
Hello,

it's fix on the new version.
